In [29]:
import numpy as np

#vector
a=np.array([1,2,3])
print(a)

[1 2 3]


In [30]:
#Matrix
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [31]:
#Tensor
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
#customized datatype
d=np.array([1,2,3],dtype=float)
print(d)

[1. 2. 3.]


In [33]:
#from 1 to 10 with step of 2
e=np.arange(1,11,2)
print(e)

[1 3 5 7 9]


In [34]:
f=np.arange(1,12,2).reshape(3,2)
print(f)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [35]:
#populate ones
g=np.ones((2,3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
#populate zeros
h=np.zeros((2,3))
print(h)

[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
#generate random numbers
i=np.random.random((3,4))
print(i)

[[0.24080647 0.61872003 0.22643009 0.85023154]
 [0.7281126  0.00825666 0.22905151 0.77491074]
 [0.58874218 0.7904053  0.55314648 0.05167776]]


In [38]:
#equally spaced from -10 to 10
j=np.linspace(-10,10,10)
print(j)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [39]:
#identity matrix
k=np.identity(3)
print(k)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
#ndim for dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [41]:
#number of item in each dimension
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 2)
(2, 2, 2)


In [42]:
#total number of itemd regardless of dimension
print(a.size)
print(b.size)
print(c.size)

3
4
8


In [43]:
#memory space occupied
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

8
8
8


In [44]:
#datatype
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [45]:
#change datatype
l=a.astype(np.float32)
print(l)

[1. 2. 3.]


In [46]:
#scalar operation (+,-,*,/,**)
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)
print(a1+2)
print(a1-2)
print(a1*2)
print(a1/2)
print(a1**2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [47]:
#vector operation
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2+a3)
print(a2-a3)
print(a2*a3)
print(a2/a3)
print(a2**a3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[        1         4        27]
 [      256      3125     46656]
 [   823543  16777216 387420489]]


In [48]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
#axis=0-->coloumn,axis=1-->row
#max/min/sum/prod
np.prod(a1,axis=1)

array([  6, 120, 504])

In [50]:
#std/var/mean/median
np.mean(a1,axis=1)

array([2., 5., 8.])

In [51]:
#ceil/floor/round
np.ceil(np.arange(3,4,0.1))

array([3., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

### Indexing and Slicing

In [52]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a2[1,0]

np.int64(4)

In [56]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
a3[1,0,1]

np.int64(5)

In [58]:
a3[1,1,0]

np.int64(6)

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1[2:5:2]

array([2, 4])

In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [63]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [64]:
a2[1,::3]

array([4, 7])

In [65]:
a2[0,:]

array([0, 1, 2, 3])

In [66]:
a2[:,2]

array([ 2,  6, 10])

In [67]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [68]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [70]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [71]:
a3[0,1,:]

array([3, 4, 5])

In [72]:
a2=np.array([1,2,3,4,5,6,7,8,9])

In [73]:
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
for i in a2:
  print(i)

1
2
3
4
5
6
7
8
9


In [75]:
for i in a1:
  print(a1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [76]:
for i in np.nditer(a1):
  print(i)

0
1
2
3
4
5
6
7
8
9


### Reshaping

### Stacking

In [77]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [79]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [80]:
# reshape

In [81]:
# Transpose
np.transpose(a2)
a2.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Splitting

In [83]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [85]:
# vertical splitting

In [86]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]