In [49]:
import numpy as np

sales_data = np.array([
    [200, 220, 250, 210, 180, 190],  # Day 1
    [230, 240, 260, 200, 195, 205],  # Day 2
    [210, 215, 255, 220, 185, 200],  # Day 3
    [205, 225, 270, 215, 190, 195],  # Day 4
    [215, 230, 265, 225, 200, 210],  # Day 5
    [225, 235, 275, 230, 205, 215],  # Day 6
    [235, 245, 280, 240, 210, 220],  # Day 7
    [245, 255, 290, 250, 215, 225],  # Day 8
    [255, 265, 300, 260, 220, 230],  # Day 9
    [265, 275, 310, 270, 225, 235]   # Day 10
])


In [50]:
#Q1a
total_sales = np.sum(sales_data,axis=0)
print("Total Sales:", total_sales)

Total Sales: [2285 2405 2755 2320 2025 2125]


In [51]:
#Q1b
avg_sales = np.mean(sales_data,axis=0)
print("Average Sales:", avg_sales)

Average Sales: [228.5 240.5 275.5 232.  202.5 212.5]


In [52]:
#Q1c
commision=sales_data*0.05
print("Commision:", commision)

Commision: [[10.   11.   12.5  10.5   9.    9.5 ]
 [11.5  12.   13.   10.    9.75 10.25]
 [10.5  10.75 12.75 11.    9.25 10.  ]
 [10.25 11.25 13.5  10.75  9.5   9.75]
 [10.75 11.5  13.25 11.25 10.   10.5 ]
 [11.25 11.75 13.75 11.5  10.25 10.75]
 [11.75 12.25 14.   12.   10.5  11.  ]
 [12.25 12.75 14.5  12.5  10.75 11.25]
 [12.75 13.25 15.   13.   11.   11.5 ]
 [13.25 13.75 15.5  13.5  11.25 11.75]]


In [53]:
#Q1d
squareroot=sales_data**0.5
print("Square Root:", squareroot)

Square Root: [[14.14213562 14.83239697 15.8113883  14.49137675 13.41640786 13.78404875]
 [15.16575089 15.49193338 16.1245155  14.14213562 13.96424004 14.31782106]
 [14.49137675 14.6628783  15.96871942 14.83239697 13.60147051 14.14213562]
 [14.31782106 15.         16.43167673 14.6628783  13.78404875 13.96424004]
 [14.6628783  15.16575089 16.2788206  15.         14.14213562 14.49137675]
 [15.         15.32970972 16.58312395 15.16575089 14.31782106 14.6628783 ]
 [15.32970972 15.65247584 16.73320053 15.49193338 14.49137675 14.83239697]
 [15.65247584 15.96871942 17.02938637 15.8113883  14.6628783  15.        ]
 [15.96871942 16.2788206  17.32050808 16.1245155  14.83239697 15.16575089]
 [16.2788206  16.58312395 17.60681686 16.43167673 15.         15.32970972]]


In [54]:
#Q2a
bonus_array = np.array([10, 20, 15, 25, 30, 5])
bonus_added = sales_data + bonus_array
print("Bonus Added:", bonus_added)

Bonus Added: [[210 240 265 235 210 195]
 [240 260 275 225 225 210]
 [220 235 270 245 215 205]
 [215 245 285 240 220 200]
 [225 250 280 250 230 215]
 [235 255 290 255 235 220]
 [245 265 295 265 240 225]
 [255 275 305 275 245 230]
 [265 285 315 285 250 235]
 [275 295 325 295 255 240]]


In [55]:
#Q2b
bonus = sales_data + 50
print("Bonus:", bonus)

Bonus: [[250 270 300 260 230 240]
 [280 290 310 250 245 255]
 [260 265 305 270 235 250]
 [255 275 320 265 240 245]
 [265 280 315 275 250 260]
 [275 285 325 280 255 265]
 [285 295 330 290 260 270]
 [295 305 340 300 265 275]
 [305 315 350 310 270 280]
 [315 325 360 320 275 285]]


In [56]:
#Q3a
np.mean(sales_data)

np.float64(231.91666666666666)

In [57]:
np.median(sales_data)

np.float64(225.0)

In [58]:
np.var(sales_data)

np.float64(870.0763888888889)

In [59]:
np.std(sales_data)

np.float64(29.49705729202303)

In [60]:
#Q3b
max=np.max(sales_data)
print(max)

310


In [61]:
min=np.min(sales_data)
print(min)

180


In [62]:
print(max-min)

130


In [63]:
#Q3c
lower_quartile = np.percentile(sales_data,25)
upper_quartile = np.percentile(sales_data,75)
iqr=upper_quartile-lower_quartile
print(iqr)

45.0


In [64]:
#Q4a
sales_data[sales_data>250]

In [69]:
#Q4b
sales_data[sales_data>300]=300
print(sales_data)

[[200 220 250 210 180 190]
 [230 240 260 200 195 205]
 [210 215 255 220 185 200]
 [205 225 270 215 190 195]
 [215 230 265 225 200 210]
 [225 235 275 230 205 215]
 [235 245 280 240 210 220]
 [245 255 290 250 215 225]
 [255 265 300 260 220 230]
 [265 275 300 270 225 235]]


In [74]:
#Q4c
cnt = np.sum((sales_data>200) & (sales_data<250))
print(cnt)

32


In [76]:
#Q4d
a=sales_data[sales_data < np.mean(sales_data)]
print(a)

[200 220 210 180 190 230 200 195 205 210 215 220 185 200 205 225 215 190
 195 215 230 225 200 210 225 230 205 215 210 220 215 225 220 230 225]


In [77]:
sales_data = np.array([
    [200, 220, 250, 210, 180, 190],  # Day 1
    [230, 240, 260, 200, 195, 205],  # Day 2
    [210, 215, 255, 220, 185, 200],  # Day 3
    [205, 225, 270, 215, 190, 195],  # Day 4
    [215, 230, 265, 225, 200, 210],  # Day 5
    [225, 235, 275, 230, 205, 215],  # Day 6
    [235, 245, 280, 240, 210, 220],  # Day 7
    [245, 255, 290, 250, 215, 225],  # Day 8
    [255, 265, 300, 260, 220, 230],  # Day 9
    [265, 275, 310, 270, 225, 235]   # Day 10
])

In [78]:
#Q5a
np.sort(sales_data[4,::])

array([200, 210, 215, 225, 230, 265])

In [84]:
#Q5b
highest=np.argmax(np.sum(sales_data,axis=1))
print(highest)

9


In [85]:
#Q5c
np.mean(sales_data,axis=0)

array([228.5, 240.5, 275.5, 232. , 202.5, 212.5])

In [86]:
#Q5d
np.mean(sales_data,axis=1)

array([208.33333333, 221.66666667, 214.16666667, 216.66666667,
       224.16666667, 230.83333333, 238.33333333, 246.66666667,
       255.        , 263.33333333])

In [88]:
#Q5e
np.mean(sales_data)

np.float64(231.91666666666666)

In [95]:
#Q6
def func(sales_data):
  return sales_data[(sales_data>np.mean(sales_data)+2*np.std(sales_data)) | (sales_data<np.mean(sales_data)-2*np.std(sales_data))]

func(sales_data)

array([300, 310])